### ISSUE TITLE
Goals of the project

### ISSUE THREAD

**Issue by o-alexandre-felipe** [gliese1337/fast-myers-diff#6]
Hi @gliese1337 , 

I would like to understand what are your plans for this package.

Initially I though t you had as a goal to keep the code small because you mentioned the size, now I noticed that you added increased the size significantly to achieve a slight speed up.

So I was wondering how what are the limits of what you want and what you don't want to include.

1. Have a function to compute only the distance, that can find application out there as well.
2. Keep readable code and reference implementations (for development), I see you don't care about it at all in the release code, for instance the change to choose data type based on size of the input you readily embraced even if it make the code not so clean.
3. Would you be interested in applying a change that speed up the computation for specific types (I have one in mind for strings)
4. Version numbers. I see that you are increasing version numbers of the NPM package whenever you change something. Do you have any reason for that? Why don't you stick to the [semantic versioning conventions](https://docs.npmjs.com/about-semantic-versioning)?
5. Do you have the intention of include a N-API implementation? 

Just to exemplify the conventional use of semantic versioning:

For instance, the first suggestion I made you moved the package from 1.0.4 to 2.0.0 (it should be 1.1.0), then when I submitted my pull request I made as 2.0.1 but on release it should be 2.1.0 (since it was backward compatible with new features), then you made some optimizations to the code and released a fully compatible version 3.0.0 (it should be 2.1.1)

**Comment by gliese1337** [comment]
> I would like to understand what are your plans for this package.

Initially, just to improve my skills as a programmer and add to my implicit GitHub resume. I liked the puzzle of figuring out the manual recursive-to-iterative transformation for the Meyers diff algorithm.

And then I wanted to publish it because the best way to ensure that you become *right* is to be wrong in public! Which worked, because it turns out there were bugs that I introduced without my tests catching them, but because it was public, you found them, and now the library is better! And to justify publishing it, I figured I needed some differentiating features, so I tried to make it small and type-agnostic, as well as minimizing memory allocation (I find writing code to minimize allocator usage is an uncommon skill in GC-managed-language development).

> Initially I though t you had as a goal to keep the code small because you mentioned the size, now I noticed that you added increased the size significantly to achieve a slight speed up.

Speed and size are both important; my main concern is simply to actually pay attention to both metrics, as unnecessary code bloat and inefficiency are rampant in modern software, and I feel a moral duty to try to combat those trends. For the most part, however, I will prioritize speed over source code size.

I have been experimenting with compilation to WASM to achieve improvements in both speed and compiled code size, but I haven't had much luck with getting that to work yet.

> Have a function to compute only the distance, that can find application out there as well.

That would be neat!

> Keep readable code and reference implementations (for development)

There are some projects where I care about having a clean reference implementation... but since this started with trying to puzzle out the iterative transformation of an originally recursive algorithm, that is not a huge priority here. Although, outside of the core internal diff algorithm, I would like to keep the various wrapper functions easy-to-read.

> Would you be interested in applying a change that speed up the computation for specific types (I have one in mind for strings).

Possibly. What did you have in mind?

> Do you have the intention of include a N-API implementation?

I have been focusing on WASM instead, because that is portable to web browsers, but an N-API option would be nice, too. I'm not sure how that would best fit in; maybe the core could be split out into a separate module, with JS, WASM, and N-API versions, with the user-facing interface pulling in whichever one is desired for a particular environment.

> Version numbers. I see that you are increasing version numbers of the NPM package whenever you change something. Do you have any reason for that? Why don't you stick to the semantic versioning conventions?

Because no one has ever seemed to consider it a particularly big deal before. Generally, my convention has been to update the minor version number for things like easy bug fixes or changes to the package structure, the middle version number for more significant improvements and sometimes additions to the API, and the major version number for major additions to the API as well as breaking changes. Because if somebody is using an older version and doesn't need new stuff, there ought to be a signal to indicate "if you upgrade, you will increase your dependency size", which might indeed be breaking for some applications.

> a fully compatible version 3.0.0 (it should be 2.1.1)

v3 is not fully backwards compatible, as I replaced the `diff_rec` function (which was poorly named anyway, since it wasn't actually recursive) with `diff_core`, which has both a different name and a different type signature. Anything just using `diff` or the other wrapper functions would not have been affected, but that is *potentially* a breaking change.

**Comment by o-alexandre-felipe** [comment]
Good point about verson 3.0.0
I never noted that diff_rec was exported.

The optimisations I imagined for strings were the ones used in fast-diff package. Doing a binary search on substrings.
The idea is that if you comparing two strings and computing substrings is much faster because 1. it is done using native code, 2. the substring implementation is frequently only a view, not an actual copy.

The approach in fast-diff handles the case where the two slices are actually equal and the case where the first character is different. The rest is done a binary search. This approach is pathological because in a situation where the common affix is much shorter than it could be the algorithm spent too much time checking first on longer slices. What I imagined is that changing slightly the algorithm for trying increasingly longer non overlapping slices. The complexity of finding a common affix of length m in two strings of length n is still O(m) (comparing up to 3*m characters) doing 2*log2(m) javascript iterations , while in the fast-diff implementation the complexity would be O(n) (doing up to 2*n characters, and 2*log2(n) javascript iterations)

The idea is nice, but in the tests for inputs of up to 1k (in node 12) I did it is not faster than the iterative character comparison maybe it would have been in older engines.
If you want to take a look here it is the code for the test I did
https://github.com/o-alexandre-felipe/fast-myers-diff/blob/65fa0c2fc71c11f2d27b3c671d8959bc56d48f3d/test/affix-test.ts#L61

I will check your other repositories :)
